### ISSUE TITLE
Canot find the CHANGELOG and docs for 0.6.0

### ISSUE THREAD

**Issue by photino** [taosdata/taos-connector-rust#149]
Our project [`zino`](https://github.com/photino/zino) is using `taos`. When upgrading the version to `0.6.0`, it fails to build. We would like to find the  CHANGELOG for the new version. Thanks!

**Comment by zitsen** [comment]
v0.6.0 changed the default connection pool from r2d2 to deadpool. So some methods' signatures has been breakingly changed. Including:

- `build()?` -> `build().await?`.
- `pool.get()?` -> `pool.get().await?`.

If you use `taos::sync::*`, you should change your Cargo.toml file:

```toml
taos = { version = "0.7", default-features = false, features = ["ws", "optin", "r2d2"] }
```

Then nothing should be changed.

**Comment by zitsen** [comment]
<https://docs.rs/taos> has been updated too.

**Comment by zitsen** [comment]
Closed. Free to reopen it if not solved
