### ISSUE TITLE
Will Value::VarBinary be fully supported?

### ISSUE THREAD

**Issue by bioinformatist** [taosdata/taos-connector-rust#166]
It seems inserting with `stmt` need `to_json_value` method, which may cause:

```pre
thread 'core::training::tests::test_register_in_parallel' panicked at 'not yet implemented'
```

as `BINARY` is such a common type in TDengine, which represents those fields with only ASCII characters.

**Comment by zitsen** [comment]
Currently VarChar is an alias of BINARY, and VarBinary is a new data type that has not been supported in TDengine.

You can use VarChar for this purpose.

**Comment by bioinformatist** [comment]
@zitsen So which type corresponds to `Binary` in TDengine? I'm sure it's ASCII character in my program so there's no need for `VarChar`.

**Comment by zitsen** [comment]
In TDengine 3.0+, the `BINARY` type is just an alias of `VARCHAR`, so, you can use the varchar type currently. `varbinary` is kept for small size of raw bytes.

Here a data type list currently supported at [SQL Data Types](https://docs.tdengine.com/taos-sql/data-type/)
