### ISSUE TITLE
unresolved import `super::Offset`

### ISSUE THREAD

**Issue by easyang** [taosdata/taos-connector-rust#185]
error[E0432]: unresolved import `super::Offset`
  --> .cargo/registry/src/github.com-1ecc6299db9ec823/taos-0.8.8/src/lib.rs:11:43
   |
11 |     pub use super::{Consumer, MessageSet, Offset, TmqBuilder};
   |                                           ^^^^^^
   |                                           |
   |                                           no `Offset` in the root
   |                                           help: a similar name exists in the module: `IsOffset`
   |
   = help: consider importing one of these items instead:
           crate::tmq::Offset
           taos_sys::tmq::Offset

**Comment by easyang** [comment]
[dependencies]
taos = { version = "*", default-features = false, features = ["native"] }

**Comment by bioinformatist** [comment]
@easyang This problem should be solved by https://github.com/taosdata/taos-connector-rust/pull/191.

You can try with the latest version and please feel easy to give any reponse here.
