### ISSUE TITLE
What is the proper executor for `exec_sync` (`query_sync`)?

### ISSUE THREAD

**Issue by bioinformatist** [taosdata/taos-connector-rust#197]
> All operations in this issue are performed in `ws` mode as:
> `taos = { version = "*", default-features = false, features = ["ws"] }`

In a special scenario we need to use the connector in blocking (synchronous) way. I've noticed that the blocking mode was implemented by `futures::executor::block_on()` in source code, but I'm not sure what is the right runtime for this, so tokio was just introduced by the error message:

![image](https://github.com/taosdata/taos-connector-rust/assets/17194719/c6bafcfb-1b21-4619-9be7-4520fbb8e097)

## Try 1: Use the default test runtime by tokio:x:

The tokio was labelled as dependency in my `Cargo.toml` (with all features enabled):

```toml
tokio = { version = "1", features = ["full"] }
```

and with the default test runtime by tokio:

```rust
#[tokio::test()]
async fn test_task_running_in_parallel() -> Result<()> {
    // ...
    taos.exec_sync("...")?
}
```

this will cause hanging:

![image](https://github.com/taosdata/taos-connector-rust/assets/17194719/bd3f55f5-b366-458e-a37c-5f9be6f30226)

## Try 2: Use the multi-threaded runtime with only one worker thread by tokio:heavy_check_mark:

The `Cargo.toml` was same to **Try 1**, but the code was changed to:

```rust
#[tokio::test(flavor = "multi_thread", worker_threads = 1)]
async fn test_task_running_in_parallel() -> Result<()> {
    // ...
    taos.exec_sync("...")?
}
```

This time the test passed.

## Try 3: Create a blocking tokio runtime by initializing an instance when necessary:heavy_check_mark:

The `Cargo.toml` was same to previous ones, but the code was changed to:

```rust
#[test]
fn test_task_running_in_parallel() -> Result<()> {
// ...
    use tokio::runtime::Runtime;
    Runtime::new().unwrap().block_on(
        async {
            taos.exec_sync("...").unwrap()
        }
    );
}
```

The test also passed.

It seems that with tokio, the `futures::executor::block_on()` can work well in **a new thread** instead of the current one.

Please also refer to this: https://github.com/tokio-rs/tokio/issues/2376#issuecomment-608687203

So which one is the best way and if there's other elegant solutions? The 3rd way is better for me since I don't want a function with an asynchronous declaration in its signature, but it's inconvenience for initializing a blocking tokio runtime everywhere.

Or shall we use `tokio::task::spawn_blocking()` instead of `futures::executor::block_on()` for `exec_sync` and `query_sync`?

**Comment by zitsen** [comment]
Maybe `futures::executor::block_on` is the write behavior if it is your expected. In our use cases, if prefer blocking mode, `use taos::prelude::sync::*`, and `exec_sync` is only provided at async traits, so runtime is not a problem.

**Comment by bioinformatist** [comment]
OHHHHHHHHHHHH
I have some misunderstandings to the synchronous mode.
I'll update my code with your suggestion and close this issue once it passes.
Thanks for such a quick response.
