### ISSUE TITLE
关于tao-ws 库中异步运行时的问题

### ISSUE THREAD

**Issue by tdcare** [taosdata/taos-connector-rust#278]
在0.5.12 版本中，会进行异步运行时的判断，当存在运行时会加入，不存在才会新建。这个行为是符合实际应用的。但在0.10.20 这个版本中，把判断取消了，直接新建了运行时，这在一些场景下无法正常使用。希望能改回0.5.12的这种模式。

0.5.12 代码
![image](https://github.com/taosdata/taos-connector-rust/assets/50525757/f39c6dea-0f39-4fc3-b38d-de890c00cfdb)

0.10.20 代码
![image](https://github.com/taosdata/taos-connector-rust/assets/50525757/e13257b4-4ea0-411c-b8eb-b79012065409)

请问这个变更是基于什么考虑，能否改回原来的模式。谢谢！

**Comment by AdamEECS** [comment]
Done: resolved in version 0.11.2.
