### ISSUE TITLE
query sometime panicked

### ISSUE THREAD

**Issue by jsamtsang** [taosdata/taos-connector-rust#314]
![11](https://github.com/taosdata/taos-connector-rust/assets/31495837/d621c65f-8306-4247-9841-2ed7701b15b6)

taos v0.12
deadpool v0.10.0
rustup v1.76.0

**Comment by bioinformatist** [comment]
Could you provide a minimal reproducible case?

**Comment by yinheli** [comment]
Unable to reproduce your issue. Could you please provide the steps or SQL statement for reproducing it? Also, could you tell us which version of TDengine you are using?
